FileExtension2AnnotationSymbol {
    FileExtension:".txt"
    AnnotationSymbol:"#"
}

FileExtension2AnnotationSymbol {
    FileExtension:".go"
    AnnotationSymbol:"//"
}

JavaScriptStartSymbol:"IT<"
JavaScriptEndSymbol:"IT>"
PreprocessorMacroForCurrentLine:"__LINE__"
PreprocessorMacroForCurrentStartLine:"__START_LINE__"
PreprocessorMacroForCurrentEndLine:"__END_LINE__"
PreprocessorMacroForCurrentFileEndLine:"__FILE_END_LINE__"
JavaScriptTableNameForDirectory:"d"
JavaScriptFunctionNameForDirectoryInsert:"i"
JavaScriptFunctionNameForDirectoryDelete:"d"
JavaScriptFunctionNameForDirectorySelectFileCount:"fc"
JavaScriptFunctionNameForDirectorySelectFileName:"fn"
JavaScriptFunctionNameForDirectoryUpdate:"u"
JavaScriptTableNameForFile:"f"
JavaScriptFunctionNameForFileInsert:"i"
JavaScriptFunctionNameForFileDelete:"d"
JavaScriptFunctionNameForFileSelectLineCount:"lc"
JavaScriptFunctionNameForFileUpdate:"u"
JavaScriptFunctionNameForFileOrigin:"o"
JavaScriptTableNameForLine:"l"
JavaScriptFunctionNameForLineInsert:"i"
JavaScriptFunctionNameForLineDelete:"d"
JavaScriptFunctionNameForLineSelect:"s"
JavaScriptFunctionNameForLineUpdate:"u"
JavaScriptFunctionNameForLineOrigin:"o"
JavaScriptTableNameForSystem:"s"
JavaScriptTableNameForSystemFunctions:"f"